export const birthdayWishes = [
  "Big smiles.",
  "Wild adventures.",
  "All the love.",
  "More happy days.",
  "Little wins.",
  "A softer world.",
  "Sunshine, always.",
  "Midnight laughter.",
  "Beautiful surprises.",
  "Unhurried mornings.",
  "Dreams coming true.",
  "New favorite places.",
  "Cake for breakfast.",
  "Music on repeat.",
  "Your kind of magic.",
  "Very good company.",
  "A little chaos.",
  "Braver little steps.",
  "Time for yourself.",
  "The best memories.",
  "Unstoppable joy.",
  "Cozy rainy days.",
  "More belly laughs.",
  "Lovely little detours.",
  "Unexpected good news.",
  "A heart full.",
  "Everything you hope for.",
  "The happiest 28.",
] as const;
